crafty/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#welcome'

  get '/signup' => 'registrations#new', :as => 'signup'
  post '/signup' => 'registrations#create'

  get '/login' => 'sessions#new', :as => 'login'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => 'logout'

  get 'tags/most_popular' => 'tags#most_popular'

  resources :users, only: [:show] do
    resources :crafts, only: [:new, :create, :show, :edit, :update]
  end

  get '/users' => 'users#index'

  resources :crafts, only: [:index]
  resources :tags, except: [:destroy]
end

crafty/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crafty/app/models/craft.rb
class Craft < ApplicationRecord
  belongs_to :user
  has_many :craft_tags
  has_many :tags, through: :craft_tags

  validates_presence_of :title, :difficulty, :description, :instructions
  validates :difficulty, inclusion: { in: %w(easy medium hard), message: "%{value} is not a valid difficulty" }

  def tags_attributes=(tags_attributes)
    tags_attributes.values.each do |tag_attributes|
      if !tag_attributes[:name].strip.empty?
        tag_name = tag_attributes[:name].downcase
        tag = Tag.find_or_create_by(name: tag_name)
        tags << tag if tag.persisted? && !tag.name.blank? && !tags.include?(tag)
      end
    end
  end
end

crafty/app/models/craft_tag.rb
class CraftTag < ApplicationRecord
  belongs_to :tag
  belongs_to :craft
end

crafty/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :craft_tags
  has_many :crafts, through: :craft_tags

  validates_uniqueness_of :name

  def self.most_popular_tags
    @max = 0
    Tag.all.each do |tag|
      if tag.crafts.count > @max
        @max = tag.crafts.count
      end
    end
    @most_popular = Tag.all.select { |tag| tag.crafts.count == @max }
  end
end

crafty/app/models/user.rb
class User < ApplicationRecord
  has_many :crafts

  has_secure_password

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: /@/, message: "address is invalid" }
  validates :password, length: { minimum: 6 }
  validates_uniqueness_of :email
end

crafty/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :is_logged_in?, :authenticate_user!, :redirect_if_not_author

  private
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def is_logged_in?
      !!current_user
    end

    def authenticate_user!
      redirect_to login_path if !is_logged_in?
    end

    def redirect_if_not_author
      if current_user.id != @craft.user_id
        redirect_to crafts_path, alert: "You do not have access to that page."
      end
    end
end

crafty/app/controllers/crafts_controller.rb
class CraftsController < ApplicationController
  before_action :authenticate_user!

  def index
    @crafts = Craft.all
    @ordered_crafts = @crafts.sort_by { |f| f['title'].upcase }
  end

  def new
    @craft = Craft.new
  end

  def create
    @user = User.find(params[:user_id])
    @craft = @user.crafts.build(craft_params)
    if @craft.save
      redirect_to user_craft_path(current_user, @craft), notice: "Craft successfully created!"
    else
      redirect_to new_user_craft_path(current_user), alert: @craft.errors.full_messages.each { |err| err }.join(". ")
    end
  end

  def edit
    @craft = Craft.find(params[:id])
    redirect_if_not_author
  end

  def update
    @craft = Craft.find(params[:id])
    redirect_if_not_author
    if @craft.update(craft_params)
      redirect_to user_craft_path(current_user, @craft), notice: "Craft successfully updated!"
    else
      redirect_to edit_user_craft_path(current_user, @craft), alert: @craft.errors.full_messages.each { |err| err }.join(". ")
    end
  end

  def show
    @craft = Craft.find_by(id: params[:id])
    @ordered_tags = @craft.tags.sort_by { |f| f['name'].downcase }
  end

  private
    def craft_params
      params.require(:craft).permit(:title, :difficulty, :description, :instructions, :picture_url, :tag_ids => [], :tags_attributes => [:name])
    end
end

crafty/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    if is_logged_in?
      redirect_to crafts_path
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to crafts_path
    else
      render "registrations/new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

crafty/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if is_logged_in?
      redirect_to crafts_path
    end
  end

  def create
    if auth.present?
      @user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
        u.password = SecureRandom.hex
      end
      session[:user_id] = @user.id
      redirect_to crafts_path, notice: "Successfully logged in!"
    else
      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to crafts_path, notice: "Successfully logged in!"
      else
        @user.nil? ? (flash[:alert] = "Email is Invalid") : (flash[:alert] = "Password is Invalid")
        render "sessions/new"
      end
    end
  end

  def destroy
    if is_logged_in?
      session.delete(:user_id)
      redirect_to root_path, notice: "Successfully logged out!"
    else
      redirect_to login_path
    end
  end

  private
    def auth
      request.env['omniauth.auth']
    end
end

crafty/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags = Tag.all
    @ordered = @tags.sort_by { |f| f['name'].downcase }
  end

  def most_popular
    @most_popular = Tag.most_popular_tags
    @ordered_tags = @most_popular.sort_by { |f| f['name'].upcase}
  end

  def show
    @tag = Tag.find(params[:id])
    @ordered_crafts = @tag.crafts.sort_by { |f| f['title'].upcase}
  end
end

crafty/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @ordered_users = @users.sort_by { |u| u['name'].upcase }
  end

  def show
    @user = User.find_by(id: params[:id])
    @ordered_crafts = @user.crafts.sort_by { |f| f['title'].upcase }
  end
end

crafty/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
  end
end

crafty/app/helpers/application_helper.rb
module ApplicationHelper
end

crafty/app/views/crafts/_form.html.erb
<%= form_for [user, craft] do |f| %>

  <div class="form-fields">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div><br>

  <div class="form-fields">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div><br>

  <div class="form-fields">
    <%= f.label :difficulty %>
    <em>(Difficulty must be 'easy', 'medium', or 'hard'.)</em>
    <%= f.text_field :difficulty %>
  </div><br>

  <div class="form-fields">
    <%= f.label :picture_url %>
    <%= f.text_field :picture_url, placeholder: "(optional)" %>
  </div><br>

  <div class="form-fields">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div><br>

  <div class="form-fields">
    Tags: <br><br>

    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br><br>

    <%= f.fields_for(:tags, @craft.tags.build) do |tag_field| %>
      <%= tag_field.label 'Create a New Tag: ' %>
      <%= tag_field.text_field :name, placeholder: "(optional)" %>
    <% end %><br><br>
  </div>

  <%= f.submit "Submit" %>
<% end %>

crafty/app/views/crafts/edit.html.erb
<h2>Edit a Craft</h2>
<hr>

<%= render 'layouts/alerts' %>

<%= render 'crafts/form', craft: @craft, user: current_user %>

<br>
<%= link_to "Cancel", user_craft_path(current_user, @craft) %>

crafty/app/views/crafts/index.html.erb
<%= render 'layouts/notices' %>
<%= render 'layouts/alerts' %>

<h2>All Crafts</h2>
<hr>

<% @ordered_crafts.each do |craft| %>
  <h3><%= craft.title %> | <%= link_to "View", user_craft_path(craft.user, craft) %></h3>
<% end %><br>

crafty/app/views/crafts/new.html.erb
<h2>Create a New Craft</h2>
<hr>

<%= render 'layouts/alerts' %>

<%= render 'crafts/form', craft: @craft, user: current_user %>

<br>
<%= link_to "Cancel", crafts_path %>

crafty/app/views/crafts/show.html.erb
<%= render 'layouts/notices' %>

<h2><%= @craft.title %></h2>
  <hr>

<% if @craft.picture_url && !@craft.picture_url.blank?%>
  <%= image_tag @craft.picture_url, width:"500px", height: "400px" %>
<% end %>

<h3>Author: <%= link_to  @craft.user.name, user_path(@craft.user) %> </h3>

<p><strong>Description: </strong><%= @craft.description %></p>

<p><strong>Level of Difficulty: </strong><%= @craft.difficulty %></p>

<p><strong>Instructions: </strong></p>
<p><%= @craft.instructions %></p>
<br>

<% if @craft.tags.last %>
<p><strong>Tags: </strong></p>
  <ul>
    <% @ordered_tags.each do |tag| %>
      <li><%= link_to tag.name, tag_path(tag) %></li>
    <% end %>
  </ul>
<br>
<% end %>

<% if current_user.id == @craft.user_id %>
  <%= link_to "Edit", edit_user_craft_path(current_user, @craft), class: "btn btn-primary" %>
<% end %>
<br><br>

crafty/app/views/layouts/_alerts.html.erb
<% if alert %>
  <div id="alert" class="alert">
    <p class="alert" style="color:red"><%= alert %></p>
  </div>
<% end %>

crafty/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Crafty</a>
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navHeaderCollapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
           <li class="active"><a href="/crafts">Home</a></li>
           <li class = "dropdown">
              <a href ="#" class = "dropdown-toggle" data-toggle = "dropdown">Crafts</a>
              <ul class = "dropdown-menu">
                <li><%= link_to "My Crafts", user_path(current_user) %></li>
                <li><%= link_to "Create New", new_user_craft_path(current_user) %></li>
              </ul>
           </li>
           <li class = "dropdown">
              <a href ="#" class = "dropdown-toggle" data-toggle = "dropdown">Tags</a>
              <ul class = "dropdown-menu">
                <li><%= link_to "All Tags", tags_path %></li>
                <li><%= link_to "Most Popular", tags_most_popular_path %></li>
              </ul>
           </li>
           <li><%= link_to "Users", users_path %></li>
           <li><%= link_to "Log Out", logout_path %></li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

crafty/app/views/layouts/_notices.html.erb
<% if notice %>
  <div id="notice" class="notice">
    <p class="notice" style="color:green"><%= notice %></p>
  </div>
<% end %>

crafty/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crafty</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
        <%= yield %>
    </div>

  </body>
</html>

crafty/app/views/tags/index.html.erb
<h2>View by Tag</h2>
<hr>

<h4>All Tags:</h4>

<% @ordered.each do |tag| %>
  <p><%= link_to tag.name, tag_path(tag) %> (<%= pluralize(tag.crafts.count, "craft") %>)</p>
<% end %>

crafty/app/views/tags/most_popular.html.erb
<h2>Most Popular Tags</h2>
<hr>
<h4>The tag(s) with the most number of crafts!</h4>
  <br>
<% @ordered_tags.each do |tag| %>
  <p><%= link_to tag.name, tag_path(tag) %> (<%= tag.crafts.count %>)</p>
<% end %>

crafty/app/views/tags/show.html.erb
<h2>All Crafts Under Tag: <%= @tag.name %></h2>
<hr>

<% @ordered_crafts.each do |craft| %>
  <p><%= link_to craft.title, user_craft_path(craft.user_id, craft) %><p>
<% end %>

crafty/app/views/users/index.html.erb
<h2>All Users</h2>
<hr>

<% @ordered_users.each do |user| %>
  <p><%= link_to user.name, user_path(user) %> (<%= pluralize(user.crafts.count, "craft") %>)</p>
<% end %>

crafty/app/views/users/show.html.erb
<h2><%= @user.name %>'s Crafts</h2>
<hr>

<% @ordered_crafts.each do |craft| %>
  <p><%= link_to craft.title, user_craft_path(@user, craft) %></p>
<% end %>

crafty/app/views/welcome/welcome.html.erb
<%= render '/layouts/notices' %>
<div class="jumbotron text-center">
  <h1>Welcome to Crafty</h1>
  <p>The app that allows you to manage your arts and crafts and share with others!</p>
  <hr>
  <p>
    <%= link_to "Signup", signup_path, class: "btn btn-primary" %>
    <%= link_to "Login", login_path, class: "btn btn-primary" %>
    <%= link_to 'Login via Facebook', '/auth/facebook', class: "btn btn-primary"%>
  </p>
</div>